steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "eu.gcr.io/$PROJECT_ID/plotly_app:1.0.0",
            "-f", "Dockerfile", ".", "--build-arg runtime_path=." ]
  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "eu.gcr.io/$PROJECT_ID/plotly_app:1.0.0" ]
